import 'bootstrap/dist/css/bootstrap.min.css';

import './globals.css'; 

import { AuthProvider } from '../components/context/AuthContext';

export const metadata = {
  title: 'E-learning Platform',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}